cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'

brew 'nvm'
brew 'diff-so-fancy'
brew 'fasd'
brew 'ffmpeg', args: ['with-libass', 'with-fontconfig']
brew 'git'
brew 'gnupg'
brew 'imagemagick', args: ['with-fontconfig']
brew 'jenv'
brew 'pyenv'
brew 'rbenv'
brew 'tree'
brew 'zsh'

cask 'alfred'
cask 'docker'
cask 'dropbox'
cask 'dynalist'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'hyper'
cask 'iterm2'
cask 'postman'
cask 'scratch'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'spotify-notifications'
cask 'telegram'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'xmind'

