cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

brew 'diff-so-fancy'
brew 'fasd'
brew 'git'
brew 'nvm'
brew 'pyenv'
brew 'rbenv'
brew 'zsh'

cask '1password'
cask 'chromium'
cask 'cron'
cask 'google-chrome'
cask 'grammarly'
cask 'iterm2'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'raindropio'
cask 'raycast'
cask 'rectangle'
cask 'rocket'
cask 'slack'
cask 'spotify'
cask 'todoist'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'
